# HOW TO USE THESE RAKE TASKS:
#
# 1. Before upgrading the Solr container, export your files
#    with rake migrate_solr:export. This will download your
#    Solr data into ./solr/exports, with one JSON file per
#    collection/tenant.
#
# 2. If the Solr schema/configset changes, edit the configuration
#    files in ./solr, and/or the path in config/settings.yml. (Or
#    pull in the schema changes using git.)
#
# 3. Run docker-compose stop. Pull in changes/change the
#    version for the Solr docker container in docker-compose.yml.
#    Then run docker-compose up -d to create the new Solr container.
#
# 4. Depending on the changes between your old and new versions
#    of Solr, your collections may not appear, or may be
#    non-functioning. Run rake migrate_solr:import to delete/recreate
#    the collection and import documents from the previous version.
#    If there are problems, you can troubleshoot using the Solr
#    Dashboard at localhost:8983.

namespace :migrate_solr do
  desc 'Exports all Solr documents for all accounts into a json file. You should only use this in a dev environment.'
  task export: [:environment] do
    Account.all.each do |account|
      solr = RSolr.connect url: account.solr_endpoint.options[:url]

      # Use an initial query to figure out the number of documents
      rows = (solr.get 'select', params: { q: "*:*" })['response']['numFound']

      # Now get all documents
      docs = (solr.get 'select', params: {
          q: "*:*",
          rows: rows
      })['response']['docs']

      export_dir = File.join(Rails.root, 'solr', 'exports')
      FileUtils.mkdir_p(export_dir)

      out_file = File.join(Rails.root, 'solr', 'exports', "#{account.tenant}.json")
      File.open(out_file,'w+') do |file|
        output = docs.map do |doc|
          # Delete keys that Solr can't import
          doc.delete('score')
          doc.delete('_version_')
          JSON.pretty_generate(doc)
        end
        file.puts "[\n"
        file.puts output.join(",")
        file.puts "]"
      end
    end
  end

  task import: [:environment] do
    desc  'Import files in Rails.root/solr/exports generated by rake migrate_solr:export.'
    export_dir = File.join(Rails.root, 'solr', 'exports')

    # Upload the Solr configuration to Zookeeper
    SolrConfigUploader.default.upload(Settings.solr.configset_source_path)
    config_name = Settings.solr.configset

    Account.all.each do |account|
      collection_name = account.solr_endpoint.options[:collection]

      # Delete and recreate the collection. If this doesn't work, you
      # may have to delete and recreate the collection using the collections
      # tab in the Solr Dashboard.
      `curl "#{Settings.solr.url}admin/collections?action=DELETE&name=#{collection_name}"`
      `curl "#{Settings.solr.url}admin/collections?action=CREATE&name=#{collection_name}&collection.configName=#{config_name}&numShards=1"`

      # Import the documents
      file = Dir.glob("#{export_dir}/*").find { |file| file.include? collection_name }
      `curl -H 'Content-Type: application/json' -d @#{file} "#{Settings.solr.url}#{collection_name}/update/json/docs?commit=true"`
      end
    end
end