terms:
  - 35 mm slide
  - Color negative
  - Black-and-white negative
  - Photographic print
  - Cassette recording
  - Video tape
  - Digital image
  - Digital video
  - Digital audio
  - Text
  - Poster
