terms:
  - Adadiem
  - Ahenkro
  - Akanyakrom
  - Ashanti Region
  - Banda
  - Bima
  - Boase
  - Bofie
  - Bondoukou
  - Bole
  - Bongase
  - Broahane
  - Brong Ahafo
  - Bui
  - Dokochina
  - Dompofie
  - Dorbour
  - Dumboli
  - Fawoman
  - Gbao
  - Jneni
  - Kabruno
  - Kanka
  - Kintampo
  - Kojie
  - Kumasi
  - Kuulo Kataa
  - Makala
  - Makala Kataa
  - Ngre Kataa
  - Northern Region
  - Nyire
  - Sabiye
  - Sanwa
  - Sase
  - Techiman
  - Wenchi
  - Wewa