terms:
  - id: https://creativecommons.org/publicdomain/mark/1.0/
    term: "Public Domain Mark 1.0"
    active: true
  - id: https://creativecommons.org/licenses/by-nc/4.0/
    term: "Creative Commons Attribution-NonCommercial"
    active: true
  - id: http://rightsstatements.org/page/InC/1.0/?language=en
    term: "In Copyright"
    active: true
  - id: http://rightsstatements.org/page/InC-OW-EU/1.0/?language=en
    term: "In Copyright - EU Orphan Work"
    active: true
  - id: http://rightsstatements.org/page/InC-EDU/1.0/?language=en
    term: "In Copyright - Educational Use Permitted"
    active: true
  - id: http://rightsstatements.org/page/InC-NC/1.0/?language=en
    term: "In Copyright - Non-Commercial Use Permitted"
    active: true
  - id: http://rightsstatements.org/page/InC-RUU/1.0/?language=en
    term: "In Copyright - Rights-holder(s) Unlocatable or Unidentifiable"
    active: true
  - id: http://rightsstatements.org/page/NoC-CR/1.0/?language=en
    term: "No Copyright - Contractual restrictions"
    active: true
  - id: http://rightsstatements.org/page/NoC-NC/1.0/?language=en
    term: "No Copyright - Non-Commercial Use Only"
    active: true
  - id: http://rightsstatements.org/page/NoC-OKLR/1.0/?language=en
    term: "No Copyright - Other Known Legal Restrictions"
    active: true
  - id: http://rightsstatements.org/page/NoC-US/1.0/?language=en
    term: "No Copyright - United States"
    active: true
  - id: http://rightsstatements.org/page/CNE/1.0/?language=en
    term: "Copyright Not Evaluated"
    active: true
  - id: http://rightsstatements.org/page/UND/1.0/?language=en
    term: "Copyright Undetermined"
    active: true
  - id: http://rightsstatements.org/page/NKC/1.0/?language=en
    term: "No Known Copyright"
    active: true
