development:
  user: <%= ENV['FCREPO_USER'] || 'fedoraAdmin' %>
  password: <%= ENV['FCREPO_PASSWORD'] || 'fedoraAdmin' %>
  url: <%= ENV['FCREPO_URL'] || "http://127.0.0.1:#{ENV.fetch('FCREPO_DEVELOPMENT_PORT', 8984)}/rest" %>
  base_path: <%= ENV['FCREPO_DEV_BASE_PATH'] %>
test:
  user: <%= ENV['FCREPO_USER'] || 'fedoraAdmin' %>
  password: <%= ENV['FCREPO_PASSWORD'] || 'fedoraAdmin' %>
  url: <%= ENV['FCREPO_URL'] || "http://127.0.0.1:#{ENV.fetch('FCREPO_TEST_PORT', 8986)}/rest" %>
  base_path: <%= ENV['FCREPO_TEST_BASE_PATH'] %>
production:
  user: <%= ENV['FCREPO_USER'] || 'fedoraAdmin' %>
  password: <%= ENV['FCREPO_PASSWORD'] || 'fedoraAdmin' %>
  url: <%= ENV['FCREPO_URL'] || "http://127.0.0.1:8983/fedora/rest" %>
  base_path: <%= ENV['FCREPO_BASE_PATH'] %>
  request:
    # Increase these numbers to lengthen the timeout for slow fcrepo queries
    timeout: 4800
    open_timeout: 4800