# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTINGS__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#
multitenancy:
  enabled: true
  default_host: "%{tenant}.localhost:3000"
  host: 'localhost:3000'
  admin_host: 'localhost:3000'
  admin_only_tenant_creation: true

#ssl_configured: true

#action_controller:
#  asset_host:

redis:
  default_namespace: hyku

solr:
  url: "http://solr:8983/solr/"
  configset: hyku
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: hyku
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:

zookeeper:
  connection_str: "localhost:9983/configs"

active_job:
  queue_adapter: :sidekiq

active_job_queue:
  url:

s3:
  upload_bucket:

# fits_path: "./fits-1.5.0/fits.sh"
fits_path: "/opt/fits-1.0.5/fits.sh"
#fits_path: "/home/sufia/fits/fits-0.8.5/fits.sh"

google_analytics_id:

# Register here: http://www.geonames.org/manageaccount
geonames_username: 'jcoyne'

# The address to which the contact form is submitted
contact_email: "user@example.com"
#
devise:
  account_signup: true
  # The address from which user invitations are sent
  invitation_from_email: "user@example.com"

oai:
  name: Vault
  url: http://vault.localhost:3000/catalog/oai
  prefix: oai:hyku
  email: change-me-in-hyku-settings@example.org
  sample_id: 806bbc5e-8ebe-468c-a188-b7c14fbe34df

# An array of IPs and IP ranges that should be allowed to access institution-only objects
allowed_ip_ranges: ["111.111.111.1"]

fast_update:
  other_changes_email: "user@example.com"

fixity_email: "user@example.com"

cache_filesystem_root: "tmp/cache"
