development:
  default:
    url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/dev" %>
  full_text:
    url: http://localhost:8983/solr/development
test:
  default:
    url: http://solr:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/test
  full_text:
    url: http://solr:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/test