zookeeper:
  connection_str: 'localhost:9985/configs'

solr:
#  url: "http://127.0.0.1:8985/solr/"
  url: "http://solr:8983/solr/test"

multitenancy:
  enabled: true
# admin_host: 'localhost'
# default_host: "%{tenant}.localhost"
