# Generated by hyrax:models
class Collection < ActiveFedora::Base

  include ::Hyrax::CollectionBehavior
  include ::CustomCollectionBehavior

  # defined in CustomCollectionBehavior for now (possibly in Hyrax 4)
  after_destroy :destroy_featured

  # Only define properties specific to collections here. Any property
  # included in all Vault models (collections, works, file sets) goes in
  # VaultBasicMetadata
  property :in_scua, predicate: ::RDF::URI.new('http://library.uvic.ca/ns/uvic#in_scua'), multiple: false

  property :date_modified, predicate: ::RDF::Vocab::DC.modified, multiple: true do |index|
    index.type :date
    index.as :stored_sortable
  end

  # These lines must appear AFTER all custom properties are declared.
  # include Hyrax::BasicMetadata
  include ::VaultBasicMetadata

  self.indexer = CollectionIndexer

end
